### ISSUE TITLE
Missing Keyboard

### ISSUE THREAD

**Issue by ivanperez-keera** [madjestic/e1337#1]
I wanted to try this to build an experiment on top of it, but I cannot compile it because `Keyboard.hs` is not there.

Any chance you could upload it if it's necessary?

**Comment by ivanperez-keera** [comment]
Mouse is also not found :(

**Comment by madjestic** [comment]
Hey, Ivan

I've uploaded Keyboard and Mouse files, try commit #2aa5dad
I've been messing with shaders, I don't think there were any breaking changes to the rest, but let me know if anything else is missing.

I've been thinking of forking it and calling a "Yampa Toy" or something, since it's more of a Shader-Toy like application as of this moment. 

Cheers,
Vlad

**Comment by ivanperez-keera** [comment]
Thanks!
